# edX Pattern Library Documentation Site: Overall Config

title:                  edX Pattern Library
short_title:            Pattern Library

tagline:                The Visual, UI, and Front End styleguide for edX's applications

author:
    name:               edX Pattern Library Team
    url:                http://www.edx.org
    email:              pattern-library@edx.org

url:                    http://ux.edx.org
url_example:            examples/
url_dummy:              http://ux.edx.org

source:                 ./pldoc

baseurl:                /
permalink:              /:categories/:title/

source:                 ./pldoc

exclude:                [
                            "node_modules",
                            "gulp",
                            "gulpfile.js",
                            "package.json",
                            "bower.json",
                            "pldoc",
                            "pattern-library",
                            "static"
                        ]

collections:
    components:
        output: true
    design_elements:
        output: true

highlighter:            rouge
